kind: ConfigMap
apiVersion: v1
metadata:
  name: loj-judgerserver-config
  namespace: default
  annotations:
    kubesphere.io/alias-name: loj-judgerserver-config
    kubesphere.io/creator: admin
data:
  JUDGE_SERVER_IP: status.podIP
  JUDGE_SERVER_NAME: judge-111
  JUDGE_SERVER_PORT: '5588'
  MAX_TASK_NUM: '-1'
  NACOS_PASSWORD: '123456'
  NACOS_URL: 'loj-nacos-service:8848'
  NACOS_USERNAME: root
  REMOTE_JUDGE_MAX_TASK_NUM: '-1'
  REMOTE_JUDGE_OPEN: 'true'
  SANDBOX_URL: 'http://loj-sandbox-service:6060'
