kind: ConfigMap
apiVersion: v1
metadata:
  name: loj-backend-config
  namespace: default
  annotations:
    kubesphere.io/alias-name: loj-backend-config
    kubesphere.io/creator: admin
data:
  BACKEND_SERVER_PORT: '4488'
  JUDGE_TOKEN: default
  JWT_TOKEN_EXPIRE: '86400'
  JWT_TOKEN_FRESH_EXPIRE: '43200'
  JWT_TOKEN_SECRET: default
  MYSQL_DATABASE_NAME: loj
  MYSQL_HOST: loj-mysql-service
  MYSQL_PORT: '3306'
  MYSQL_PUBLIC_HOST: loj-mysql-service
  MYSQL_PUBLIC_PORT: '3306'
  MYSQL_ROOT_PASSWORD: '123456'
  MYSQL_USERNAME: root
  NACOS_PASSWORD: '123456'
  NACOS_URL: 'loj-nacos-service:8848'
  NACOS_USERNAME: root
  REDIS_HOST: loj-redis-mysql
  REDIS_PASSWORD: '123456'
  REDIS_PORT: '6379'
