mybatis-plus:
  mapper-locations: classpath*:com/github/loj/mapper/xml/**Mapper.xml
  type-aliases-package: com.github.loj.pojo.entity
  configuration:
    cache-enabled: true
  # 关闭打印 mybatis-plus 的 LOGO
  global-config:
    banner: false

# 消费者将要去访问的微服务名称（注册成功进入nacos的微服务提供者）
service-url:
  name: loj-judgeserver # 服务名
