apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: default
  labels:
    app: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nacos
  template:
    metadata:
      labels:
        name: nacos
    spec:
      containers:
        - name: nacos:1.4
          image: nacos
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  labels:
    app: nacos
spec:
  type: NodePort
  ports:
    - port: 8848
      protocol: TCP
      name: nacos
      targetPort: 8848
      nodePort: 32380
  selector:
    name: nacos