kind: Deployment
apiVersion: apps/v1
metadata:
  name: loj-frontend
  namespace: default
  labels:
    app: loj-frontend
  annotations:
    deployment.kubernetes.io/revision: '3'
    kubesphere.io/alias-name: loj-frontend
    kubesphere.io/creator: admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loj-frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: loj-frontend
      annotations:
        kubesphere.io/restartedAt: '2024-03-17T10:52:39.651Z'
    spec:
      containers:
        - name: loj-frontend
          image: 'registry.cn-hangzhou.aliyuncs.com/lxhcaicai/loj-frontend:1.0'
          env:
            - name: BACKEND_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: loj-frontend
                  key: BACKEND_SERVER_HOST
            - name: BACKEND_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: loj-frontend
                  key: BACKEND_SERVER_PORT
            - name: SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  name: loj-frontend
                  key: SERVER_NAME
            - name: USE_HTTPS
              valueFrom:
                configMapKeyRef:
                  name: loj-frontend
                  key: USE_HTTPS
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
