version: "1"
services:

  loj-redis:
    image: redis
    container_name: loj-redis
    restart: always
    volumes:
      - ${LOJ_DATA_DIRECTORY}/data/redis/data:/data
    networks:
      loj-network:
        ipv4_address: ${REDIS_HOST:-172.20.0.2}
    ports:
      - ${REDIS_PORT:-6379}:6379
    command: redis-server --requirepass ${REDIS_PASSWORD:-123456} --appendonly yes

  loj-mysql:
    image: loj-mysql
    container_name: loj-mysql
    restart: always
    volumes:
      - ${LOJ_DATA_DIRECTORY}/data/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-123456} # mysql数据库root账号的密码
      - TZ=Asia/Shanghai
      - NACOS_USERNAME=${NACOS_USERNAME:-root} # 后续nacos所用管理员账号
      - NACOS_PASSWORD=${NACOS_PASSWORD:-123456} # 后续nacos所用管理员密码
    ports:
      - ${MYSQL_PUBLIC_PORT:-3306}:3306
    networks:
      loj-network:
        ipv4_address: ${MYSQL_HOST:-172.20.0.3}

networks:
  loj-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET:-172.20.0.0/16}